management.endpoints.web.exposure.include: "*"
spring:
  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password: 
    url: jdbc:h2:file:C:/data/dm_db;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
      poolName: HikariPoolZZZ
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
    show-sql: true
    properties.format_sql: true
    properties.hibernate.generate_statistics: false
  h2:
    console.path: /h2
custom.h2.tcpport: 9091
